# Generated by Django 5.0.1 on 2024-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('NORMAL_USER', 'Normal User'), ('RADIOLOGIST', 'Radiologist'), ('TELERADIOLOGIST', 'Teleradiologist'), ('SURGEON', 'Surgeon')], max_length=20),
        ),
    ]
