# Generated by Django 5.0.1 on 2024-04-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_owner',
        ),
    ]
