# Generated by Django 5.0.1 on 2024-04-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Normal User', 'Normal User'), ('Surgeon', 'Surgeon'), ('Teleradiologist', 'Teleradiologist'), ('Radiologist', 'Radiologist')], default='Normal User', max_length=20),
        ),
    ]
