# Generated by Django 5.0.1 on 2024-04-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_org_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
